/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

import java.io.File;
import javax.swing.JDesktopPane;
import javax.swing.JTree;
import javax.swing.SwingUtilities;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.MutableTreeNode;

/**
 *
 * @author Diego Carcamo
 */
public class ExploradorES extends javax.swing.JPanel {

    /**
     * Creates new form ExploreadoEs
     */
    
    JDesktopPane panel;
    File SelectedFile;
    File Ruta;
    
    
    
    public ExploradorES(File Ruta,JDesktopPane Desktop) {
        
        this.panel= Desktop;
        this.Ruta=Ruta;
        
        initComponents();
        
    
        Actualizar(Ruta);
        
    }

    public File getSelectedFile() {
        return SelectedFile;
    }
    
    
    
    
    
    
    
    
    
    

    public JTree getArbol() {
        return Arbol;
        
        
        
        
        
        
        
        
        
    }
    
    
    
    
    public void SelectFile(){
    
        SelectedFile= new File("Z/"+Arbol.getSelectionPath().toString().replace("[","").replace(", ","\\\\").replace("]",""));
        System.out.println(Arbol.getSelectionPath().toString());
        System.out.println(SelectedFile.getPath());
        
        
        
        
        
    
    
    
    }
    
    
    
    
    
    
    
   public void CrearArbol(File Ruta,DefaultMutableTreeNode model){
            System.out.println("Creando Arbol");
            
                //Casos donde la recurisvidad es util
            
                
                
        if(Ruta!=null && Ruta.exists() && Ruta.isDirectory()){
            
            
            
            
  
            for(File item:Ruta.listFiles()){
                
                 
                DefaultMutableTreeNode nodo= new DefaultMutableTreeNode(item.getName());
            
                if(item.isDirectory()){
                
                    CrearArbol(item,nodo);
  
                }
                
                model.add(nodo);
                
                    
            
            
            
            
            }
            
   
   
   
   
        }
                  
    
    
    
    
    }
   
   
   public void abrirBloc(){
        //Se abre el blco de notasa   
        
        BlocNotas bloc= new BlocNotas(Ruta,panel);
        
        bloc.setPathArchivo(SelectedFile);
        bloc.ArbriArhivo();
        System.out.println("opcion 3");
    
    
       
   
   
   
   }
   
        
        
    public void ClickDerecho(java.awt.event.MouseEvent evt ){
    
       MenuEs.show(Arbol, evt.getX(), evt.getY());
        
        
    
    
    }
    
    
    public void Actualizar(File ruta){
        
        
        DefaultMutableTreeNode Raiz= new DefaultMutableTreeNode(ruta.getName());
        DefaultTreeModel Ramas= new DefaultTreeModel(Raiz);
        Arbol.setModel(Ramas);

        
        
        CrearArbol(ruta, Raiz);
        

       
        
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuEs = new javax.swing.JPopupMenu();
        Crear = new javax.swing.JMenuItem();
        JOptionEliminar = new javax.swing.JMenuItem();
        JAbrir = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        Arbol = new javax.swing.JTree();

        MenuEs.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MenuEs.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                MenuEsPopupMenuWillBecomeVisible(evt);
            }
        });

        Crear.setText("Crear");
        Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearActionPerformed(evt);
            }
        });
        MenuEs.add(Crear);

        JOptionEliminar.setText("Eliminar");
        JOptionEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JOptionEliminarActionPerformed(evt);
            }
        });
        MenuEs.add(JOptionEliminar);

        JAbrir.setText("Abrir");
        JAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JAbrirActionPerformed(evt);
            }
        });
        MenuEs.add(JAbrir);

        Arbol.setBackground(new java.awt.Color(102, 102, 102));
        Arbol.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Arbol.setForeground(new java.awt.Color(204, 153, 0));
        Arbol.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Arbol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ArbolMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Arbol);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ArbolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ArbolMouseClicked
        // TODO add your handling code here:
        if(panel!=null){
            if(SwingUtilities.isRightMouseButton(evt)){
            ClickDerecho(evt);
            

        }
    
    
        }
        
        
        
        
    }//GEN-LAST:event_ArbolMouseClicked

    private void CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearActionPerformed
        // TODO add your handling code here:
        System.out.println("pollo asado");
    }//GEN-LAST:event_CrearActionPerformed

    private void JAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JAbrirActionPerformed
        // TODO add your handling code here:
        SelectFile();
        abrirBloc();
        
        System.out.println("Abriendo");
    }//GEN-LAST:event_JAbrirActionPerformed

    private void JOptionEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JOptionEliminarActionPerformed
        // TODO add your handling code here:
        
        
        
        
        
    }//GEN-LAST:event_JOptionEliminarActionPerformed

    private void MenuEsPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_MenuEsPopupMenuWillBecomeVisible
        // TODO add your handling code here:
        SelectFile();
    }//GEN-LAST:event_MenuEsPopupMenuWillBecomeVisible


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree Arbol;
    private javax.swing.JMenuItem Crear;
    private javax.swing.JMenuItem JAbrir;
    private javax.swing.JMenuItem JOptionEliminar;
    private javax.swing.JPopupMenu MenuEs;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
