/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import java.awt.BorderLayout;
import java.awt.desktop.OpenFilesEvent;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import minios.Directorios;
import minios.User;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author Diego Carcamo
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    
    
    ArrayList<User> Usuarios=new ArrayList<>();
    
    
    
    //Lectores de archivo
    
  

    
    
    
    IniciarSesion Login ;
    User Cuenta;
    
    Directorios LoggedDir;
    
    public Frame() {
        
        
        
        
      
        
        
        
        Login= new IniciarSesion();
        ObtenerInicio();
        
        
        initComponents();
        AddLogin();
        
        LoggedDir= new Directorios();
        
      
    }
    
    
     
    
    public void ObtenerInicio(){
        
        ActionListener accion = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Cuenta=Login.getLoggedUser();
                if(Cuenta!=null){
                    Login.dispose();
                    JOptionPane.showConfirmDialog(null, "Bienvenido Usuario","Soy mensanje",JOptionPane.OK_OPTION);
                    
                      System.out.println(Cuenta.getDir().getAbsolutePath());
                      LoggedDir= new Directorios(Cuenta.getDir().getName(),null);
                      //Se setea la carpeta raiz de ese usuario
                      
                      
                   
                    
                    
               
                    
               
                 
                    
                   
                    
                  
                    
                
                }
                
                
            }
        };
        
        Login.getIniciar().addActionListener(accion);
                
         
    
    
    
    
    }
    
    
   
    
    public void AddLogin(){
        
        Login.setSize(600,400);
        Login.setResizable(false);
        Login.setLocation(200,40);
        Login.setResizable(true);
        Login.setVisible(true);
        Login.setClosable(false);
        
        Desktop.add(Login);
        Desktop.validate();
      
        
       

        
        
        
    
    
    
    
    
    }
    
    
    
    
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Mensaje = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        MainPan = new javax.swing.JPanel();
        Desktop = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Reproductor = new javax.swing.JButton();
        Imagenes = new javax.swing.JButton();
        Archivos = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Windows.png"))); // NOI18N

        Mensaje.setResizable(false);
        Mensaje.setSize(new java.awt.Dimension(200, 300));

        jLabel2.setBackground(new java.awt.Color(255, 0, 102));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Bienvenido");

        javax.swing.GroupLayout MensajeLayout = new javax.swing.GroupLayout(Mensaje.getContentPane());
        Mensaje.getContentPane().setLayout(MensajeLayout);
        MensajeLayout.setHorizontalGroup(
            MensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MensajeLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        MensajeLayout.setVerticalGroup(
            MensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MensajeLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPan.setBackground(new java.awt.Color(102, 102, 102));
        MainPan.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );

        MainPan.add(Desktop, java.awt.BorderLayout.CENTER);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton1.setText("Inicio");
        jPanel1.add(jButton1);

        Reproductor.setText("Mp3");
        jPanel1.add(Reproductor);

        Imagenes.setText("Imagenes");
        jPanel1.add(Imagenes);

        Archivos.setText("Explorador");
        Archivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ArchivosMouseClicked(evt);
            }
        });
        jPanel1.add(Archivos);

        jButton5.setText("Bloc");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jPanel1.add(jButton5);

        MainPan.add(jPanel1, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(MainPan, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        
        BlocNotas bloc= new BlocNotas(Cuenta.getDir());
        
        Desktop.add(bloc);
        bloc.setSize(600,400);
        bloc.setLocation(100, 50);
        bloc.setVisible(true);
        
        
        
        
        
        System.out.println("breindo Bloc de notas");
    }//GEN-LAST:event_jButton5MouseClicked

    private void ArchivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ArchivosMouseClicked
        // TODO add your handling code here:
        Explorador MisArhivos= new Explorador(Cuenta.getDir());     
        Desktop.add(MisArhivos);
        MisArhivos.setSize(600,400);
        MisArhivos.setLocation(300, 200);
        MisArhivos.setVisible(true);
        
    }//GEN-LAST:event_ArchivosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Archivos;
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JButton Imagenes;
    private javax.swing.JPanel MainPan;
    private javax.swing.JDialog Mensaje;
    private javax.swing.JButton Reproductor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
