/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interfaz;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;


import minios.User;
import minios.UserManager;

/**
 *
 * @author Diego Carcamo
 */
public class IniciarSesion extends javax.swing.JInternalFrame implements Protocolos{

    /**
     * Creates new form IniciarSesion
     */
   //El directorio se vuelve Z parecera mejor una inteface 
    final private File Dir;
    
   //
    
    private File SubDir;    
   //
    
   


    
    
    String loggedUser;
    

    

    

    
    
    
    UserManager Manager;
    public IniciarSesion() {
        
        Manager= new UserManager();
        
        

        
        
        initComponents();
        Dir= new File("Z");
 
        
        if(Dir.mkdirs()){
            System.out.println("Bienvenidos se creo la unidad Z");
        
        }
        SubDir=null;
        
        
       
    }
    
    


    public JButton getIniciar() {
        return Iniciar;
    }
    
    

    public JButton getRegistrar() {
        return registrar;
    }

    public String getLoggedUser() {
        return loggedUser;
    }
    
    
    
    
    
    
    public void Regis(String Name, String Password){
        
        try {
            if(Manager.AddUser(Name, Password)){
                //Algun mensaje
                System.out.println("Agrgado");
                
                
                CrearUserDir(Name);
                String[] carpetas= {"Mis Documentos","Mi Musica","Mis Imagagenes"};
                File Carpetas;
                for(String tag:carpetas){
                    Carpetas= new File("Z//"+Name+"//"+tag);
                    
                    Carpetas.mkdirs();
                    
                    
                    mensaje.setText("Excelente");
                
                
                }
                
            }else{
                mensaje.setText("Lo siento Usuario exsitente");
                 NameField.validate();
                this.Password.validate();
            
            
            }
        } catch (IOException ex) {
            
            
            
            System.out.println("Error IOExceptio");
           
        }
           
    
    
    
    
    
    }
    
    public void Login(String name, String paswword){
        try {
            if(Manager.login(name,paswword)){
                System.out.println("Bienvenido");
                
                loggedUser= Manager.getLoged();
                System.out.println(loggedUser);
                
        
                
                
            }else{
                mensaje.setText("No se encontro el usaurio ");
                
                NameField.validate();
                Password.validate();
                
                
            
            }
        } catch (IOException ex) {
            Logger.getLogger(IniciarSesion.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    
    
    }
    
    
    

    
    
    
    
    
    
    public void CrearUserDir(String Name){
        
        String Sub= Dir.getAbsolutePath()+"\\"+Name;
        //Se cambia el directorio
        SubDir= new File(Sub);
       
        
        
        if(SubDir.mkdir()){
            System.out.println("se a crado una carpeta con el nombre de "+ Name);
             System.out.println(SubDir.getAbsolutePath());
             
             
             
             
             
            
        
        }
        
        
        
        
                
        
        
        
    
    
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Iniciar = new javax.swing.JButton();
        NameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Password = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mensaje = new javax.swing.JLabel();
        registrar = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        Iniciar.setText("Iniciar");
        Iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IniciarMouseClicked(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Password");

        mensaje.setText("       ");

        registrar.setText("Registrar");
        registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NameField, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(Password))
                        .addGap(141, 141, 141))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))))
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(Iniciar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registrar)
                .addGap(0, 127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Iniciar)
                    .addComponent(registrar))
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarMouseClicked
        // TODO add your handling code here:
        Iniciar();
        
        
        
    }//GEN-LAST:event_IniciarMouseClicked

    private void registrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarMouseClicked
        // TODO add your handling code here:
       Crear();
    }//GEN-LAST:event_registrarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Iniciar;
    private javax.swing.JTextField NameField;
    private javax.swing.JTextField Password;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mensaje;
    private javax.swing.JButton registrar;
    // End of variables declaration//GEN-END:variables

    @Override
    public void Iniciar() {
        
        Login(NameField.getText(),Password.getText());

        
        
        
    }

    @Override
    public void Cerrar() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void Crear() {
        
        Regis(NameField.getText(),Password.getText());
        
       
        

        
    }
}
