/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;

import minios.User;
import minios.UserManager;

/**
 *
 * @author Diego Carcamo
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    
    

    
    
    
    UserManager Manager;

    IniciarSesion Login ;

    String User;

    
    File Ruta;
    
    
    MusicPlayer reproductor;
    
    public MainFrame() {      
        Manager= new UserManager();     
        Login= new IniciarSesion();
        Ruta=null;

        ObtenerInicio();
        initComponents();
        AddLogin();
        
        
        
        

        
        
        
        
      
    }

    
    
     
    
    public void ObtenerInicio(){
        
        
        
        ActionListener accion = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                
                JButton btn= (JButton) e.getSource();
                if(btn.getText().equals("Iniciar")){
                    
                    
                    
                    User=Login.getLoggedUser();
                    if(User!=null){
                         Ruta=new File("Z//"+User);
                        System.out.println("Inicianodo");
                        
                        
                        Login.dispose();
                        BarraTareas.setVisible(true);
                    
                    }
                   
                    
                    
                    
                
                
                
                
                
                
                
                }
               
                      
                   
                    
                    
               
                    
               
                 
                    
                   
                    
                  
                    
                
                
                
                
            }
        };
        
        Login.getIniciar().addActionListener(accion);

         
    
    
    
    
    }
    
    
   
    
    public void AddLogin(){
        
        Login.setSize(600,400);
        Login.setResizable(false);
        Login.setLocation(200,40);
        Login.setResizable(true);
        Login.setVisible(true);
        Login.setClosable(false);
        
        Desktop.add(Login);
        Desktop.validate();
        
        BarraTareas.setVisible(false);
        
        
      
        
       

        
        
        
    
    
    
    
    
    }
    
    
    
    public void OpenCMD(){
    
        CMD cmd= new CMD(Ruta,Desktop);
        
        cmd.setSize(600,400);
        
        
        cmd.setLocation(200,50);
        
        Desktop.add(cmd);
        cmd.setVisible(true);
    
    
    
    }
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mensaje = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        MainPan = new javax.swing.JPanel();
        Desktop = new javax.swing.JDesktopPane();
        BarraTareas = new javax.swing.JPanel();
        CmdBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Imagenes = new javax.swing.JButton();
        Reproductor = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        Archivos = new javax.swing.JButton();

        Mensaje.setResizable(false);
        Mensaje.setSize(new java.awt.Dimension(200, 300));

        jLabel2.setBackground(new java.awt.Color(255, 0, 102));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Bienvenido");

        javax.swing.GroupLayout MensajeLayout = new javax.swing.GroupLayout(Mensaje.getContentPane());
        Mensaje.getContentPane().setLayout(MensajeLayout);
        MensajeLayout.setHorizontalGroup(
            MensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MensajeLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        MensajeLayout.setVerticalGroup(
            MensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MensajeLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPan.setBackground(new java.awt.Color(102, 102, 102));
        MainPan.setLayout(new java.awt.BorderLayout());

        Desktop.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                DesktopComponentHidden(evt);
            }
        });

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );

        MainPan.add(Desktop, java.awt.BorderLayout.CENTER);

        BarraTareas.setBackground(new java.awt.Color(30, 101, 132));
        BarraTareas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        CmdBtn.setBackground(new java.awt.Color(30, 101, 132));
        CmdBtn.setText("CMD");
        CmdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdBtnActionPerformed(evt);
            }
        });
        BarraTareas.add(CmdBtn);

        jButton1.setBackground(new java.awt.Color(30, 101, 132));
        jButton1.setForeground(new java.awt.Color(30, 101, 132));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/application_office_windows_2475.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        BarraTareas.add(jButton1);

        Imagenes.setBackground(new java.awt.Color(30, 101, 132));
        Imagenes.setForeground(new java.awt.Color(153, 153, 153));
        Imagenes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/images_canon_camera_1746.png"))); // NOI18N
        Imagenes.setBorder(null);
        BarraTareas.add(Imagenes);

        Reproductor.setBackground(new java.awt.Color(30, 101, 132));
        Reproductor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/mp3_file_25822.png"))); // NOI18N
        Reproductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReproductorActionPerformed(evt);
            }
        });
        BarraTareas.add(Reproductor);

        jButton5.setBackground(new java.awt.Color(30, 101, 132));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Notepad_23093.png"))); // NOI18N
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        BarraTareas.add(jButton5);

        Archivos.setBackground(new java.awt.Color(30, 101, 132));
        Archivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Explorer3_icon-icons.com_55525.png"))); // NOI18N
        Archivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ArchivosMouseClicked(evt);
            }
        });
        Archivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArchivosActionPerformed(evt);
            }
        });
        BarraTareas.add(Archivos);

        MainPan.add(BarraTareas, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(MainPan, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        
        BlocNotas bloc= new BlocNotas(Ruta,Desktop);
        
        
        
        
        Desktop.add(bloc);
        bloc.setSize(600,400);
        bloc.setLocation(100, 50);

        bloc.setVisible(true);
        
        
        
        
        
        System.out.println("breindo Bloc de notas");
    }//GEN-LAST:event_jButton5MouseClicked

    private void ArchivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ArchivosMouseClicked
        // TODO add your handling code here:
        
        System.out.println(Ruta.getAbsolutePath());
        Explorador MisArhivos= new Explorador(Ruta,Desktop);     
        Desktop.add(MisArhivos);

        
        
        MisArhivos.setSize(600,400);
        
        
        MisArhivos.setLocation(300, 200);
        
        
        MisArhivos.setVisible(true);
        
        
        
    }//GEN-LAST:event_ArchivosMouseClicked

    private void ReproductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReproductorActionPerformed
        // TODO add your handling code here:
        reproductor= new MusicPlayer(Ruta.getAbsolutePath(),Desktop);
        
        
        
    }//GEN-LAST:event_ReproductorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DesktopComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_DesktopComponentHidden
        // TODO add your handling code here:
             
                    
                    
    }//GEN-LAST:event_DesktopComponentHidden

    private void CmdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdBtnActionPerformed
        // TODO add your handling code here:
     OpenCMD();
    }//GEN-LAST:event_CmdBtnActionPerformed

    private void ArchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArchivosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ArchivosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Archivos;
    private javax.swing.JPanel BarraTareas;
    private javax.swing.JButton CmdBtn;
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JButton Imagenes;
    private javax.swing.JPanel MainPan;
    private javax.swing.JDialog Mensaje;
    private javax.swing.JButton Reproductor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
